# Generated by Django 4.0.2 on 2022-02-17 11:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='city',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='city_filter',
            field=models.CharField(choices=[('or', 'OR'), ('not', 'NOT'), ('and', 'AND')], default='and', max_length=10, verbose_name='filter'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='department',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='team',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='team_filter',
            field=models.CharField(choices=[('or', 'OR'), ('not', 'NOT'), ('and', 'AND')], default='or', max_length=10, verbose_name='filter'),
        ),
    ]
