# Generated by Django 4.0.2 on 2022-02-17 13:51

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_telegramgroup_city_telegramgroup_city_filter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramgroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='history',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='city',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[('ABADIANIA', 'ABADIANIA'), ('ALEXANIA', 'ALEXANIA'), ('ANAPOLIS', 'ANAPOLIS'), ('CAMPO LIMPO', 'CAMPO LIMPO'), ('COCALZINHO', 'COCALZINHO'), ('DF', 'DF'), ('GOIANESIA', 'GOIANESIA'), ('NEROPOLIS', 'NEROPOLIS'), ('OURO VERDE', 'OURO VERDE'), ('SOBRADINHO', 'SOBRADINHO'), ('TRINDADE', 'TRINDADE')], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='department',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('BUROCRATICO', 'BUROCRATICO'), ('CANCELAMENTO', 'CANCELAMENTO'), ('COMERCIAL INTERNO', 'COMERCIAL INTERNO'), ('CONTABILIDADE', 'CONTABILIDADE'), ('CONTROLE DE ROTAS', 'CONTROLE DE ROTAS'), ('ENGENHARIA', 'ENGENHARIA'), ('ESTOQUE', 'ESTOQUE'), ('FINANCEIRO', 'FINANCEIRO'), ('GENTE E GESTÃO', 'GENTE E GESTÃO'), ('JURIDICO', 'JURIDICO'), ('LANÇAMENTO DE CABOS', 'LANÇAMENTO DE CABOS'), ('MARKETING', 'MARKETING'), ('MECANICA', 'MECANICA'), ('NOC INFRAESTRUTURA', 'NOC INFRAESTRUTURA'), ('NOC SUPORTE NIVEL 2', 'NOC SUPORTE NIVEL 2'), ('NOVOS PROJETOS', 'NOVOS PROJETOS'), ('OBRAS E MANUTENÇÕES', 'OBRAS E MANUTENÇÕES'), ('RETENÇÃO', 'RETENÇÃO'), ('SERVICE DESK', 'SERVICE DESK'), ('SERVICE DESK FINANCEIRO', 'SERVICE DESK FINANCEIRO'), ('SERVIÇOS GERAIS', 'SERVIÇOS GERAIS'), ('TÉCNICOS', 'TÉCNICOS'), ('VENDAS EXTERNAS', 'VENDAS EXTERNAS')], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='team',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('CANCELAMENTO', 'CANCELAMENTO'), ('COMERCIAL INTERNO', 'COMERCIAL INTERNO'), ('CONTABILIDADE', 'CONTABILIDADE'), ('CONTRATOS', 'CONTRATOS'), ('CONTROLE DE ROTAS', 'CONTROLE DE ROTAS'), ('COORDENAÇÃO FINANCEIRO E RETENÇÃO', 'COORDENAÇÃO FINANCEIRO E RETENÇÃO'), ('DESLIGADOS', 'DESLIGADOS'), ('DIRETORIA', 'DIRETORIA'), ('ENGENHARIA CAMPO', 'ENGENHARIA CAMPO'), ('ENGENHARIA INTERNO', 'ENGENHARIA INTERNO'), ('ESTOQUE', 'ESTOQUE'), ('FINANCEIRO', 'FINANCEIRO'), ('GENTE E GESTÃO', 'GENTE E GESTÃO'), ('JURÍDICO', 'JURÍDICO'), ('LANÇAMENTO DE CABOS', 'LANÇAMENTO DE CABOS'), ('MARKETING', 'MARKETING'), ('MECANICA', 'MECANICA'), ('NOC', 'NOC'), ('NOC INFRAESTRUTURA', 'NOC INFRAESTRUTURA'), ('NOC SUPORTE NIVEL 2', 'NOC SUPORTE NIVEL 2'), ('RETENÇÃO', 'RETENÇÃO'), ('SERVICE DESK', 'SERVICE DESK'), ('SERVICE DESK FINANCEIRO', 'SERVICE DESK FINANCEIRO'), ('SERVICE DESK SUPERVISÃO', 'SERVICE DESK SUPERVISÃO'), ('SERVIÇOS GERAIS', 'SERVIÇOS GERAIS'), ('TECNOLOGIA', 'TECNOLOGIA'), ('TÉCNICOS', 'TÉCNICOS'), ('VENDAS EXTERNAS', 'VENDAS EXTERNAS'), ('VENDAS EXTERNAS GESTORES', 'VENDAS EXTERNAS GESTORES'), ('VENDAS EXTERNAS GUIOMAR', 'VENDAS EXTERNAS GUIOMAR'), ('VENDAS EXTERNAS JONATAS', 'VENDAS EXTERNAS JONATAS'), ('VENDAS EXTERNAS KLEITON', 'VENDAS EXTERNAS KLEITON'), ('VENDAS EXTERNAS LARISSA', 'VENDAS EXTERNAS LARISSA'), ('VENDAS EXTERNAS THAIS', 'VENDAS EXTERNAS THAIS'), ('VENDAS EXTERNAS VICTOR HUGO', 'VENDAS EXTERNAS VICTOR HUGO')], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='team_filter',
            field=models.CharField(choices=[('or', 'OR'), ('not', 'NOT'), ('and', 'AND')], default='and', max_length=10, verbose_name='filter'),
        ),
    ]
