# Generated by Django 4.0.2 on 2022-02-17 14:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_history_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='company',
            field=app.models.ChoiceArrayField(base_field=models.CharField(choices=[('EXP', 'EXP'), ('FFC', 'FFC'), ('JB', 'JB'), ('LIPS', 'LIPS'), ('MAB', 'MAB'), ('NMF', 'NMF'), ('PVZ', 'PVZ'), ('RFA', 'RFA'), ('SGR', 'SGR'), ('TCAR', 'TCAR'), ('TCR', 'TCR'), ('WRC', 'WRC')], max_length=254), blank=True, default=list, help_text='Leave empty for all', size=None),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='company_filter',
            field=models.CharField(choices=[('or', 'OR'), ('not', 'NOT'), ('and', 'AND')], default='and', max_length=10, verbose_name='filter'),
        ),
    ]
