# Generated by Django 4.0.2 on 2022-02-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_telegramgroup_company_telegramgroup_company_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField()),
                ('missing', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('h1', models.IntegerField()),
                ('h2', models.IntegerField()),
                ('h3', models.IntegerField()),
                ('h4', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('missing_days', models.IntegerField()),
                ('proposals', models.IntegerField()),
                ('dt', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='PeriodSummarie',
        ),
    ]
