# Generated by Django 3.2.12 on 2022-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_journey_delete_periodsummarie'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramgroup',
            name='extra_time',
            field=models.BooleanField(default=True),
        ),
    ]
