# Generated by Django 3.2.12 on 2022-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_telegramgroup_extra_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='overnight_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
