# Generated by Django 3.2.12 on 2022-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_journey_overnight_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='dt',
        ),
        migrations.AddField(
            model_name='journey',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
