# Generated by Django 3.2.12 on 2022-03-18 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220318_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
